### ISSUE TITLE
Error trying to send email - send_mail

### ISSUE THREAD

**Issue by vader7071** [Alex23rodriguez/ezmail#1] opened 2023-05-31 00:55 UTC
I have been reading the documentation, and I am getting an error:

```
TypeError: unsupported operand type(s) for |: type and type
ezmail_py, line 13

Python was asked to do an operation with an object which doesn't support it
````

This is my code:
````
from pathlib import Path
from ezmail import send_mail

attachments = [
  Path("/home/pi/Documents/speedtest/speedtest.csv"),
]

envfile = Path("/home/pi/.speed_env")

send_mail(
  subject="Weekly Log",
  recipients=["usr@domain.com"]
  message="Attached weekly log"
  attachments=attachments,
  envfile=envfile
)
````
My env file is named as above (.speed_env) and looks like this:

```
USERNAME="username"
PASSWORD="password"
SMTP="smtp.gmail.com"
PORT=465
```

Obviously, my user and pass are different, but they are enclosed in quotes.

**Comment by Alex23rodriguez** [comment] 2023-05-31 15:22
Hello. What version of python are you using? It seems to be a problem with the type hints. If I’m reading the error correctly, seems to relate to [PEP 604](https://peps.python.org/pep-0604/) which was apparently added in 3.10.

I might consider rewriting the module to make it compatible with older versions.

**Comment by vader7071** [comment] 2023-05-31 15:57
I am running python 3.9. That is the current default python loaded in the Raspberry Pi OS (64-bit Bullseye)

**Comment by Alex23rodriguez** [comment] 2023-05-31 16:41
I've made some changes for backwards compatibility, if you'd like to test them out.
try running `pip install --upgrade ezmail` and running the file again.

Please note that gmail can be a bit finicky to work with. I've added the option `verbose=True` as a parameter to `send_mail` to debug what is going wrong with the SMTP connection, in case of issues

**Comment by Alex23rodriguez** [comment] 2023-06-02 19:31
I've since tested this in 3.9 and seems to work as intended. I'm closing this issue.

**Closed as completed by Alex23rodriguez** 2023-06-02 19:31 UTC
